// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfYAMR7hldR9tk6YRXPX6Cgx1JsYKM6c',
    appId: '1:824018582418:web:176cd97b97481101825f4b',
    messagingSenderId: '824018582418',
    projectId: 'videocall-app-ae4cf',
    authDomain: 'videocall-app-ae4cf.firebaseapp.com',
    storageBucket: 'videocall-app-ae4cf.appspot.com',
    measurementId: 'G-DG4K2Y9XFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhO4vfsG6O62xFjUeA1mIGP2WJ9AlyRU',
    appId: '1:824018582418:android:01bdbc7232ef3203825f4b',
    messagingSenderId: '824018582418',
    projectId: 'videocall-app-ae4cf',
    storageBucket: 'videocall-app-ae4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1Tj-HKU1H3-fAc8l26Zz4Q857kW2Cag',
    appId: '1:824018582418:ios:a22221973f9218ce825f4b',
    messagingSenderId: '824018582418',
    projectId: 'videocall-app-ae4cf',
    storageBucket: 'videocall-app-ae4cf.appspot.com',
    iosBundleId: 'com.example.videoCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1Tj-HKU1H3-fAc8l26Zz4Q857kW2Cag',
    appId: '1:824018582418:ios:a22221973f9218ce825f4b',
    messagingSenderId: '824018582418',
    projectId: 'videocall-app-ae4cf',
    storageBucket: 'videocall-app-ae4cf.appspot.com',
    iosBundleId: 'com.example.videoCallApp',
  );
}
